### ISSUE TITLE
Schema management query error "sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1049, "Unknown database 'buzz_base_report'")"

### ISSUE THREAD

**Issue by VerRan** [aws-samples/generative-bi-using-rag#7]
When i use schema magement, there is  a  error for no database "buzz_base_report", but when i created the connection the database name is "xa_bi".  I used "buzz_base_report" when I first created the connection. It seems that a cache was used here, because the cache was not updated and the wrong database name was obtained, so please help analyze it.

**Comment by VerRan** [comment]
After I used profile management to re-fetch table definition, the problem was solved, can I directly fetch the table definition when creating the profile.

**Comment by supinyu** [comment]
Hello, thank you for your feedback. We will try to modify this logic.

**Comment by supinyu** [comment]
We have fixed this issue and welcome you to contact us if you have any questions.
